apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    env: prod
    apptype: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      env: prod
      apptype: frontend
  template:
    metadata:
      labels:
        env: prod
        apptype: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        #naman